{{ config(schema='L2_PROCESSING') }}

-- models/example/SALESTARGET.sql

SELECT
    S.STOREID,
    E.EMPLOYEEID,
    P.PRODUCTID,
    D.YEAR,
    D.MONTH,
    D.QUARTER,
    SUM(OI.QUANTITY * OI.UNITPRICE) AS TARGET_SALES
FROM
    ADMIN_OMS.L1_LANDING.ORDERS O
JOIN
    ADMIN_OMS.L1_LANDING.ORDERITEMS OI ON O.ORDERID = OI.ORDERID
JOIN
    ADMIN_OMS.L1_LANDING.PRODUCTS P ON OI.PRODUCTID = P.PRODUCTID
JOIN
    ADMIN_OMS.L1_LANDING.STORES S ON O.STOREID = S.STOREID
JOIN
    ADMIN_OMS.L1_LANDING.EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID
JOIN
    ADMIN_OMS.L1_LANDING.DATES D ON DATE(O.ORDERDATE) = DATE(D.DATE)
WHERE
    D.YEAR = 2023
GROUP BY
    S.STOREID,
    E.EMPLOYEEID,
    P.PRODUCTID,
    D.YEAR,
    D.MONTH,
    D.QUARTER