version: 2

sources:
  - name: ADMIN_OMS
    tables:
      - name: CUSTOMERS
        description: "Customers table containing raw customer data."
      - name: ORDERITEMS
        description: "Order items table with pricing details."
      - name: ORDERS
        description: "Orders table containing order metadata."
      - name: PRODUCTS
        description: "Products table for product metadata."
      - name: STORES
        description: "Stores table for store identifiers."
      - name: EMPLOYEES
        description: "Employees table with employee identifiers."
      - name: DATES
        description: "Dates table for temporal data."

models:
  - name: CUSTOMER_STG
    description: "Stage table for customer data with combined names and contact info."
    columns:
      - name: CUSTOMERID
        description: "Unique identifier for each customer."
        tests:
          - not_null
          - unique
      - name: CUSTOMERNAME
        description: "Concatenated first and last name."
      - name: UPDATED_AT
        description: "Timestamp of the last update."
        tests:
          - not_null

  - name: ORDER_ITEMS_STG
    description: "Stage table for order items, calculating total price."
    columns:
      - name: ORDERITEMID
        description: "Unique identifier for each order item."
        tests:
          - not_null
          - unique
      - name: ORDERID
        description: "Identifier linking back to the order table."
        tests:
          - not_null
      - name: TOTALPRICE
        description: "Calculated total price for each order item."
        tests:
          - not_null
      - name: UPDATED_AT
        description: "Timestamp of the last update."
        tests:
          - not_null

  - name: ORDER_STG
    description: "Stage table for orders with status descriptions."
    columns:
      - name: ORDERID
        description: "Unique order identifier."
        tests:
          - not_null
          - unique
      - name: STATUSCD
        description: "Code representing order status."
      - name: STATUSDESC
        description: "Human-readable status description."
        tests:
          - not_null
      - name: UPDATED_AT
        description: "Timestamp of the last update."
        tests:
          - not_null

  - name: ORDERS_FACT
    description: "Fact table aggregating order details with calculated revenue."
    columns:
      - name: ORDERID
        description: "Unique order identifier."
        tests:
          - not_null
          - unique
      - name: REVENUE
        description: "Total revenue generated by each order."
        tests:
          - not_null

  - name: SALESTARGET
    description: "Calculates target sales for each store by product and employee for given time periods."
    columns:
      - name: STOREID
        description: "Unique identifier for stores."
        tests:
          - not_null
      - name: EMPLOYEEID
        description: "Unique identifier for employees."
        tests:
          - not_null
      - name: PRODUCTID
        description: "Unique identifier for products."
        tests:
          - not_null
      - name: YEAR
        description: "Year for which sales are calculated."
        tests:
          - not_null
      - name: MONTH
        description: "Month for which sales are calculated."
        tests:
          - not_null
      - name: QUARTER
        description: "Quarter for which sales are calculated."
        tests:
          - not_null
      - name: TARGET_SALES
        description: "Calculated target sales."
        tests:
          - not_null

  - name: STORES_PERFORMANCE
    description: "Analyzes actual vs. target sales performance for each store."
    columns:
      - name: STOREID
        description: "Unique identifier for stores."
        tests:
          - not_null
          - unique
      - name: ACTUALSALES
        description: "Sum of actual sales completed."
        tests:
          - not_null
      - name: TARGETSALES
        description: "Sum of target sales set."
        tests:
          - not_null

  - name: QUATERSALESPERCENT
    description: "Calculates percentage of sales achieved by store for the current quarter."
    columns:
      - name: STOREID
        description: "Unique identifier for stores."
        tests:
          - not_null
          - unique
      - name: ACTUALSALES
        description: "Calculated sum of actual sales by store."
        tests:
          - not_null
      - name: TARGETSALES
        description: "Sales target sum for the store."
        tests:
          - not_null
      - name: PERCENT_SALES_ACHIEVED
        description: "Percentage of target sales achieved."
        tests:
          - not_null    