{{ config(schema='L2_PROCESSING') }}

SELECT
    OS.STOREID,
    SUM(OFACT.REVENUE) AS ACTUALSALES,
    SUM(ST.TARGET_SALES) AS TARGETSALES
FROM
    {{ ref('ORDER_STG')}} OS
JOIN
    {{ ref('ORDERS_FACT')}} OFACT
ON OS.ORDERID = OFACT.ORDERID
JOIN
    {{ ref('SALESTARGET')}} ST 
ON ST.STOREID = OS.STOREID
GROUP BY 1