{{ config(schema='L2_PROCESSING', materialized='table') }}

SELECT
    OS.STOREID,
    SUM(OFACT.REVENUE) AS ACTUALSALES,
    SUM(ST.TARGET_SALES) AS TARGETSALES,
    CASE 
        WHEN SUM(ST.TARGET_SALES) > 0 THEN 
            (SUM(OFACT.REVENUE) / SUM(ST.TARGET_SALES)) * 100
        ELSE 0
    END AS PERCENT_SALES_ACHIEVED
FROM
    {{ ref('ORDER_STG') }} OS
JOIN
    {{ ref('ORDERS_FACT') }} OFACT ON OS.ORDERID = OFACT.ORDERID
JOIN
    {{ ref('SALESTARGET') }} ST ON ST.STOREID = OS.STOREID
GROUP BY 
    OS.STOREID